CREATE OR REPLACE FUNCTION CANCEL_DELETE_WORK_ORDER() RETURNS TRIGGER AS $$
BEGIN
 	IF OLD.work_date >= CURRENT_DATE - INTERVAL '2 years' THEN
 		RAISE NOTICE 'The date is too recent - cancelling delete operation';
 		RETURN NULL;
 	ELSE
 		RETURN OLD;
 	END IF;
END
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE TRIGGER CANCEL_DELETE_WORK_ORDER
BEFORE DELETE ON WORK_ORDER
FOR EACH ROW EXECUTE FUNCTION CANCEL_DELETE_WORK_ORDER();

--TEST

SELECT * FROM WORK_ORDER
WHERE WORK_ORDER_ID = 1;

UPDATE WORK_ORDER
SET WORK_DATE = CURRENT_DATE
WHERE WORK_ORDER_ID = 1; 

DELETE FROM work_order WHERE work_order_id=1; --Nie da się usunąć, trigger działa!

UPDATE WORK_ORDER
SET WORK_DATE = CURRENT_DATE - INTERVAL '4 YEAR'
WHERE WORK_ORDER_ID = 1; 

DELETE FROM work_order WHERE work_order_id=1; --Udało się usunąć !
