CREATE OR REPLACE VIEW WORK_ORDER_DETAILS AS
SELECT C.FIRST_NAME,
	C.LAST_NAME,
	G.DIOPTER_LEFT,
	G.DIOPTER_RIGHT,
	WO.PRICE
FROM WORK_ORDER AS WO
JOIN CLIENT AS C ON WO.CLIENT_ID = C.CLIENT_ID
JOIN GLASSES AS G ON G.GLASSES_ID = WO.GLASSES_ID
JOIN FRAME AS F ON F.FRAME_ID = G.FRAME_ID;


CREATE OR REPLACE VIEW CLIENT_BAD_PHONE AS
SELECT C.CLIENT_ID,
	C.ADDRESS_ID,
	C.LAST_NAME,
	C.FIRST_NAME,
	C.PHONE_NUMBER
FROM CLIENT AS C
WHERE LENGTh(C.PHONE_NUMBER) < 11
WITH LOCAL CHECK OPTION --SPRAWDZA WARUNEK PRZED MODYFIKACJA REKORDU

